apply from: "${gradleScriptDir}/release/fullJars.gradle"

jar {
    enabled = false
}

project(":powermock-release:powermock-easymock") {

    description = "Single jar containing binaries for PowerMock core, EasyMock and all test framework modules."

    def shadowDependencies = [
            project(":powermock-reflect"),
            project(":powermock-core"),
            project(":powermock-classloading:powermock-classloading-base"),
            project(":powermock-api:powermock-api-support"),
            project(":powermock-api:powermock-api-easymock"),
            project(":powermock-modules:powermock-module-junit4-common"),
            project(":powermock-modules:powermock-module-junit4"),
            project(":powermock-modules:powermock-module-junit4-legacy"),
            project(":powermock-modules:powermock-module-testng"),
            project(":powermock-modules:powermock-module-testng-common")
    ]

    dependencies {
        runtimeOnly shadowDependencies
    }

    shadowJar {
        shadowDependencies.each {
            from(it.sourceSets.main.allSource) {
                include "**/*.java"
            }
        }
    }
}

project(":powermock-release:powermock-mockito2") {

    description = "Single jar containing binaries for PowerMock core, Mockito 2.x and all test framework modules."

    def shadowDependencies = [
            project(":powermock-reflect"),
            project(":powermock-core"),
            project(":powermock-classloading:powermock-classloading-base"),
            project(":powermock-api:powermock-api-support"),
            project(":powermock-api:powermock-api-mockito2"),
            project(":powermock-modules:powermock-module-junit4-common"),
            project(":powermock-modules:powermock-module-junit4"),
            project(":powermock-modules:powermock-module-junit4-legacy"),
            project(":powermock-modules:powermock-module-testng"),
            project(":powermock-modules:powermock-module-testng-common")
    ]

    dependencies {
        runtimeOnly shadowDependencies
    }

    shadowJar {
        shadowDependencies.each {
            from(it.sourceSets.main.allSource) {
                include "**/*.java"
            }
        }
    }
}

project(":powermock-release:powermock-easymock-junit") {

    description = "Single jar containing binaries for PowerMock core, JUnit and EasyMock modules."

    dependencies {
        api(project(path:":powermock-release:powermock-easymock", configuration: "shadow"))
        api("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        api("org.easymock:easymock:${easymockVersion}")
        api("org.objenesis:objenesis:${objenesisVersion}")
        api("org.javassist:javassist:${javassistVersion}")
        api("cglib:cglib-nodep:${cglibVersion}")
    }
}

project(":powermock-release:powermock-easymock-testng") {

    description = "Single jar containing binaries for PowerMock core, TestNG and EasyMock modules."

    dependencies {
        api(project(path:":powermock-release:powermock-easymock", configuration: "shadow"))
        api("org.testng:testng:${testngVersion}")
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        api("org.easymock:easymock:${easymockVersion}")
        api("org.objenesis:objenesis:${objenesisVersion}")
        api("org.javassist:javassist:${javassistVersion}")
        api("cglib:cglib-nodep:${cglibVersion}")
    }
}

project(":powermock-release:powermock-mockito2-junit") {

    description = "Single jar containing binaries for PowerMock core, JUnit and Mockito modules."

    dependencies {
        api(project(path:":powermock-release:powermock-mockito2", configuration: "shadow"))
        api("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        api("org.mockito:mockito-core:${mockitoVersion}"){
            exclude group: 'net.bytebuddy', module: 'byte-buddy'
            exclude group: 'net.bytebuddy', module: 'byte-buddy-agent'
        }
        api("org.objenesis:objenesis:${objenesisVersion}")
        api("org.javassist:javassist:${javassistVersion}")
        api("cglib:cglib-nodep:${cglibVersion}")
    }
}

project(":powermock-release:powermock-mockito2-testng") {

    description = "Single jar containing binaries for PowerMock core, TestNG and Mockito modules."

    dependencies {
        api(project(path:":powermock-release:powermock-mockito2", configuration: "shadow"))
        api("org.testng:testng:${testngVersion}")
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        api("org.mockito:mockito-core:${mockitoVersion}"){
            exclude group: 'net.bytebuddy', module: 'byte-buddy'
            exclude group: 'net.bytebuddy', module: 'byte-buddy-agent'
        }
        api("org.objenesis:objenesis:${objenesisVersion}")
        api("org.javassist:javassist:${javassistVersion}")
        api("cglib:cglib-nodep:${cglibVersion}")
    }
}