repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

group = "org.powermock"

apply plugin: 'java'

// 'provided' scope, formerly supplied by the propdeps plugin (repo.spring.io/plugins-release is gone, HTTP 401)
configurations { provided }
sourceSets.main.compileClasspath += configurations.provided
sourceSets.test.compileClasspath += configurations.provided
sourceSets.test.runtimeClasspath += configurations.provided

targetCompatibility = 1.8
sourceCompatibility = 1.8

tasks.withType(JavaCompile) {
    options.warnings = false
}

if (JavaVersion.current() == JavaVersion.VERSION_1_8) {
    apply plugin: 'checkstyle'
    checkstyle {
        toolVersion = checkstyleVersion
        configFile = rootProject.file('config/checkstyle/checkstyle.xml')
    }
}

test{
    exclude "**/*Defect*", "**/*TestCase*"
}

