def publishableModules = allprojects - rootProject - project(":powermock-api") - project(":powermock-classloading") - project(":powermock-modules") - project(":tests") - project(":tests").subprojects - project(":powermock-release") - project(":powermock-release").subprojects

configure(publishableModules) { project ->
    apply from: "${gradleScriptDir}/java-module.gradle"
    apply from: "${gradleScriptDir}/publishing/publishable-module.gradle"
}

def skippedTasksForUnpublishableModules = [
    'generatePomFileForJavaLibraryPublication',
    'publishJavaLibraryPublicationToMavenLocal',
    'javadoc',
    'javadocJar',
    'sourcesJar',
    'install'
]

def unpublishableModules = allprojects - publishableModules - project(":powermock-release").subprojects
configure(unpublishableModules) { project ->
    project.tasks.all {
        if(skippedTasksForUnpublishableModules.contains(it.name)) {
            it.enabled = false
        }
    }
}

def skippedTasksForGenericModules = [
    'generatePomFileForJavaLibraryPublication',
    'publishJavaLibraryPublicationToMavenLocal',
    'jar',
    'javadoc',
    'javadocJar',
    'sourcesJar'
]

def genericModules = project(":powermock-release").subprojects
configure(genericModules) { project ->
    project.tasks.all {
        if (skippedTasksForGenericModules.contains(it.name)) {
            it.enabled = false
        }
    }
}

if (project.hasProperty('checkJava6Compatibility') && !System.getenv("SKIP_RELEASE")) {
    //if we're skipping release, let's also skip checking compatibility (faster builds)
    configure(publishableModules) { project ->
        project.apply plugin: 'ru.vyarus.animalsniffer'
        project.dependencies {
            signature 'org.codehaus.mojo.signature:java18:1.0@signature'
        }
    }
}

project(":powermock-reflect") {
    description = "Various utilities for accessing internals of a class."

    dependencies {
        api("org.objenesis:objenesis:${objenesisVersion}")
        api("net.bytebuddy:byte-buddy:${byteBuddy}")
        api("net.bytebuddy:byte-buddy-agent:${byteBuddy}")
        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
        testImplementation("cglib:cglib-nodep:${cglibVersion}")
    }
}

project(":powermock-core") {
    description = "Various utilities for accessing internals of a class."

    dependencies {
        api(project(":powermock-reflect"))
        api("org.javassist:javassist:${javassistVersion}")
        api("net.bytebuddy:byte-buddy:${byteBuddy}")
        api("net.bytebuddy:byte-buddy-agent:${byteBuddy}")

        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
        testImplementation("com.github.stefanbirkner:system-rules:${systemRulesVersion}")
        testImplementation(project(":tests:utils"))

        testImplementation("org.mockito:mockito-core:${mockitoVersion}"){
            exclude group: 'net.bytebuddy', module: 'byte-buddy'
            exclude group: 'net.bytebuddy', module: 'byte-buddy-agent'
        }
    }
}

project(":powermock-api") {
    jar {
        enabled = false
    }
}

project(":powermock-api:powermock-api-support") {
    description = "PowerMock API Utility classes."

    dependencies {
        api(project(":powermock-reflect"))
        api(project(":powermock-core"))
        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-api:powermock-api-easymock") {
    description = "PowerMock API for EasyMock."

    dependencies {
        api(project(":powermock-api:powermock-api-support"))
        api("cglib:cglib-nodep:${cglibVersion}")
        api("org.easymock:easymock:${easymockVersion}")

        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}



project(":powermock-api:powermock-api-mockito2"){
    description = "PowerMock API for Mockito 2.+.."

    dependencies {

        api(project(":powermock-api:powermock-api-support"))
        api("org.mockito:mockito-core:${mockitoVersion}"){
            exclude group: 'net.bytebuddy', module: 'byte-buddy'
            exclude group: 'net.bytebuddy', module: 'byte-buddy-agent'
        }

        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")

        testImplementation(project(":tests:utils"))
    }
}

project(":powermock-classloading") {
    jar {
        enabled = false
    }
}

project(":powermock-classloading:powermock-classloading-base") {
    description = "Utilities for loading and executing classes."

    dependencies {
        api(project(":powermock-api:powermock-api-support"))
        api(project(":powermock-reflect"))
        api(project(":powermock-core"))
        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-classloading:powermock-classloading-objenesis") {
    description = "Performs classloader deep-cloning using Objenesis."

    dependencies {
        api(project(":powermock-classloading:powermock-classloading-base"))
        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-classloading:powermock-classloading-xstream") {
    description = "Performs classloader deep-cloning using X-Stream."

    dependencies {
        api(project(":powermock-classloading:powermock-classloading-base"))
        api("com.thoughtworks.xstream:xstream:${xstreamVersion}")
        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-modules") {
    jar {
        enabled = false
    }
}

project(":powermock-modules:powermock-module-javaagent") {
    description = "PowerMock Java agent support."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }

    jar {
        manifest {
            attributes(
                    "Manifest-Version": "1.0",
                    "Premain-Class": "org.powermock.modules.agent.PowerMockAgent",
                    "Agent-Class": "org.powermock.modules.agent.PowerMockAgent",
                    "Can-Retransform-Classes": true,
                    "Can-Redefine-Classes": true
            )
        }
    }
}

project(":powermock-modules:powermock-module-junit4-common") {
    description = "PowerMock support module for all versions of JUnit 4.x."

    dependencies {
        api(project(":powermock-reflect"))
        api(project(":powermock-core"))
        api("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-modules:powermock-module-junit4") {
    description = "PowerMock support module for JUnit 4.x."

    dependencies {
        api(project(":powermock-modules:powermock-module-junit4-common"))
        api("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
        testImplementation("org.easymock:easymock:${easymockVersion}")
    }
}

project(":powermock-modules:powermock-module-junit4-legacy") {
    description = "PowerMock support module for JUnit 4.0-4.3."

    dependencies {
        api(project(":powermock-modules:powermock-module-junit4-common")) {
            exclude group: 'junit', module: 'junit'
        }
        api("junit:junit:4.3") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}


project(":powermock-modules:powermock-module-junit4-rule") {
    description = "PowerMock support module for JUnit 4.x rules."

    dependencies {
        api(project(":powermock-core"))
        api(project(":powermock-modules:powermock-module-junit4-common"))

        provided(project(":powermock-classloading:powermock-classloading-base"))

        api("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}


project(":powermock-modules:powermock-module-junit4-rule-agent") {
    description = "PowerMock support module for JUnit 4.x rules with Java agent"

    dependencies {
        api(project(":powermock-core"))
        api(project(":powermock-modules:powermock-module-javaagent"))

        api("junit:junit:${junitVersion}") {
            exclude group: 'org.hamcrest', module: 'hamcrest-core'
        }
        api("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-modules:powermock-module-testng-common") {
    description = "PowerMock module for TestNG. Common classes"

    dependencies {
        api(project(":powermock-reflect"))
        api(project(":powermock-core"))
        api("org.testng:testng:${testngVersion}")
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-modules:powermock-module-testng") {
    description = "PowerMock module for TestNG."

    dependencies {
        api(project(":powermock-core"))
        api(project(":powermock-modules:powermock-module-testng-common"))
        api("org.testng:testng:${testngVersion}")
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-modules:powermock-module-testng-agent") {
    description = "PowerMock module for TestNG with using Javaagent."

    dependencies {
        api(project(":powermock-core"))
        api(project(":powermock-modules:powermock-module-testng-common"))
        api(project(":powermock-modules:powermock-module-javaagent"))
        api("org.testng:testng:${testngVersion}")
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }
}

project(":powermock-modules:powermock-module-junit5") {
    description = "PowerMock module for JUnit Jupiter (JUnit 5)."

    dependencies {
        api(project(":powermock-core"))
        api("org.junit.jupiter:junit-jupiter-api:5.14.4")
    }
}

configure(publishableModules) { project ->
    apply from: "${gradleScriptDir}/release/publish-jar.gradle"

}