/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.powermock.core;

import org.powermock.core.classloader.MockClassLoader;

import java.lang.reflect.Method;
import java.security.ProtectionDomain;

/**
 * Defines classes generated by PowerMock (replicas, concrete subclasses) without
 * requiring java.lang to be opened to unnamed modules.
 * <p>
 * javassist's {@code CtClass#toClass(ClassLoader, ProtectionDomain)} calls the protected
 * {@code ClassLoader#defineClass} via {@code setAccessible}, which is denied on JDK 16+
 * unless {@code java.lang} is opened. This helper
 * <ol>
 * <li>uses the public {@link MockClassLoader#defineClass(String, ProtectionDomain, byte[])}
 * when the target loader is a {@link MockClassLoader},</li>
 * <li>otherwise defines the class in the target loader reflectively, as javassist did
 * (works on JDK 8-15 and when {@code java.lang} is opened), and</li>
 * <li>if that is denied, defines it in a dedicated child class loader of the target loader.</li>
 * </ol>
 * The generated classes live in their own packages ({@code replica.*}, {@code subclass.*})
 * and only use public members of other classes, so a child loader is sufficient.
 * <p>
 * Internal API. It is public, and its signature uses JDK types only, because callers such as
 * {@link ClassReplicaCreator} may be loaded by a {@link MockClassLoader} (together with
 * their own copy of javassist) while this class is loaded by the parent class loader.
 */
public final class GeneratedClassDefiner {

    private GeneratedClassDefiner() {
    }

    public static Class<?> define(String name, byte[] bytes, ClassLoader loader, ProtectionDomain protectionDomain) {
        if (loader instanceof MockClassLoader) {
            return ((MockClassLoader) loader).defineClass(name, protectionDomain, bytes);
        }
        if (loader != null) {
            final Method defineClass = accessibleDefineClass();
            if (defineClass != null) {
                try {
                    return (Class<?>) defineClass.invoke(loader, name, bytes, 0, bytes.length, protectionDomain);
                } catch (java.lang.reflect.InvocationTargetException e) {
                    final Throwable cause = e.getCause();
                    if (cause instanceof RuntimeException) {
                        throw (RuntimeException) cause;
                    }
                    if (cause instanceof Error) {
                        throw (Error) cause;
                    }
                    throw new RuntimeException(cause);
                } catch (IllegalAccessException e) {
                    // fall through to the child class loader
                }
            }
        }
        return new ChildClassLoader(loader).define(name, bytes, protectionDomain);
    }

    private static Method accessibleDefineClass() {
        try {
            Method method = ClassLoader.class.getDeclaredMethod("defineClass",
                    String.class, byte[].class, int.class, int.class, ProtectionDomain.class);
            method.setAccessible(true);
            return method;
        } catch (NoSuchMethodException e) {
            return null;
        } catch (SecurityException e) {
            return null;
        } catch (RuntimeException e) {
            // java.lang.reflect.InaccessibleObjectException on JDK 9+ when java.lang is not opened.
            return null;
        }
    }

    private static final class ChildClassLoader extends ClassLoader {
        ChildClassLoader(ClassLoader parent) {
            super(parent);
        }

        Class<?> define(String name, byte[] bytes, ProtectionDomain protectionDomain) {
            return defineClass(name, bytes, 0, bytes.length, protectionDomain);
        }
    }
}
