/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.powermock.core;

import java.security.ProtectionDomain;

/**
 * Defines classes generated by PowerMock (replicas, concrete sub-classes) in a
 * fresh child class loader of a given parent.
 * <p>
 * Javassist's {@code CtClass.toClass(ClassLoader, ProtectionDomain)} injects the
 * class into an existing class loader by calling the protected
 * {@code ClassLoader.defineClass} reflectively, which the module system forbids
 * on Java 16+ unless {@code java.lang} is opened. A sub-class of
 * {@link ClassLoader} may call {@code defineClass} directly, so this works on
 * every Java version without opening java.base to PowerMock. The generated classes are
 * only ever referenced through the returned {@code Class} object, never looked
 * up by name, so living in a child loader is transparent to callers.
 * <p>
 * Internal class. It is public because {@code MockClassLoader} does not load it
 * itself, so callers loaded by a mock class loader must reach it across loaders.
 * For the same reason its signature uses JDK types only (a mock class loader
 * may have its own copy of javassist).
 */
public final class GeneratedClassLoader extends ClassLoader {

    private GeneratedClassLoader(ClassLoader parent) {
        super(parent);
    }

    public static Class<?> define(String name, byte[] bytecode, ClassLoader parent, ProtectionDomain protectionDomain) {
        return new GeneratedClassLoader(parent).defineClass(name, bytecode, 0, bytecode.length, protectionDomain);
    }
}
