List easymock = [
        "org.easymock:easymock:${easymockVersion}",
        "org.assertj:assertj-core:${assertjVersion}",
        "org.hamcrest:hamcrest-core:${hamcrestVersion}",
        project(":powermock-api:powermock-api-easymock"),
        project(":tests:utils")
]

project(":tests:easymock:junit4-agent") {
    description = "Tests for PowerMock Java agent with JUnit4 and Easymock"

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:${junitVersion}")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-javaagent"))
        testImplementation(project(":powermock-modules:powermock-module-junit4-rule-agent"))
    }

    def pathToAgent = project(":powermock-modules:powermock-module-javaagent").jar.outputs.files.getFiles().getAt(0)

    test {
        jvmArgs "-javaagent:${pathToAgent}"
    }
}

project(":tests:easymock:junit4-legacy"){
    description = "Tests for EasyMock module with JUnit 4.0-4.3."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.3")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4-legacy"))
    }
}

project(":tests:easymock:junit4"){
    description = " Tests for EasyMock module with JUnit 4.x"

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.4")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4")){
            exclude group: 'junit', module: 'junit'
        }
    }

    test{
        exclude "**/*Defect*"
    }
}

project(":tests:easymock:junit45"){
    description = " Tests for EasyMock module with JUnit 4.5."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.5")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4")){
            exclude group: 'junit', module: 'junit'
        }
        testImplementation files(project(":tests:easymock:junit4").sourceSets.test.output)
    }

    test{
        exclude "**/*Defect*"
    }
}

project(":tests:easymock:junit47"){
    description = " Tests for EasyMock module with JUnit 4.7."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.7")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4")){
            exclude group: 'junit', module: 'junit'
        }
        testImplementation files(project(":tests:easymock:junit4").sourceSets.test.output)
    }
}

project(":tests:easymock:junit48"){
    description = " Tests for EasyMock module with JUnit 4.8."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.8.2")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4")){
            exclude group: 'junit', module: 'junit'
        }
        testImplementation files(project(":tests:easymock:junit4").sourceSets.test.output)
    }
}

project(":tests:easymock:junit410"){
    description = " Tests for EasyMock module with JUnit 4.10."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.10")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4")){
            exclude group: 'junit', module: 'junit'
        }
        testImplementation files(project(":tests:easymock:junit4").sourceSets.test.output)
    }
}

project(":tests:easymock:junit412"){
    description = " Tests for EasyMock module with JUnit 4.12."

    dependencies {
        api(project(":powermock-core"))
        testImplementation("junit:junit:4.12")
        testImplementation easymock
        testImplementation(project(":powermock-modules:powermock-module-junit4")){
            exclude group: 'junit', module: 'junit'
        }
        testImplementation files(project(":tests:easymock:junit4").sourceSets.test.output)
    }
}

project(":tests:easymock:testng"){
    description = "Tests for EasyMock module with TestNG."

    dependencies {
        api(project(":powermock-core"))
        api(project(":powermock-modules:powermock-module-testng"))
        testImplementation easymock
        testImplementation("org.testng:testng:${testngVersion}")
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
    }

    test{
        useTestNG(){
            suites 'suite.xml'
        }
    }
}

project(":tests:easymock:testng-agent"){
    description = "Tests for EasyMock module with TestNG."

    dependencies {
        api(project(":powermock-core"))
        api(project(":powermock-modules:powermock-module-testng"))
        testImplementation easymock
        testImplementation("org.testng:testng:${testngVersion}")
        testImplementation("org.hamcrest:hamcrest-core:${hamcrestVersion}")
        testImplementation("org.assertj:assertj-core:${assertjVersion}")
        testImplementation(project(":powermock-modules:powermock-module-testng-agent"))
    }

    def pathToAgent = project(":powermock-modules:powermock-module-javaagent").jar.outputs.files.getFiles().getAt(0)

    test {
        useTestNG(){
            suites 'suite.xml'
        }

        jvmArgs "-javaagent:${pathToAgent}"
    }
}